### ISSUE TITLE
Facebook, total posts error

### ISSUE THREAD

**Issue by MarkG000** [beeminder-capstone/Nectar-Backend#6]
On https://beemindernectar.herokuapp.com/goals/new?metric_key=total_posts&provider_name=facebook
I am getting 

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

For what it's worth, friends/likes count work fine.

**Comment by tdulcet** [comment]
Are you sure? That link works fine for me and I am not seeing anything in the logs. When did you see that error? 

Thanks again for all your feedback!

**Comment by MarkG000** [comment]
Tried again just now (13:55 GMT), same thing. In case your log keeps IP addresses, it is 212.233.40.38

**Comment by tdulcet** [comment]
Thanks for the details. Looks like it is a timeout error:
`2017-08-14T13:55:34.110616+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/goals/new?metric_key=total_posts&provider_name=facebook" host=beemindernectar.herokuapp.com request_id=0c0fd7c3-3ce2-47b1-b654-4992150239bc fwd="212.233.40.38" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https`

It took 41 seconds to make the Facebook API calls to count your posts and Heroku pages [timeout after 30 seconds](https://devcenter.heroku.com/articles/request-timeout). I will try to find a solution to this. In the meantime, if you need to add this goal, you should be able to do so from the Nectar mobile app. The actual hourly sync with Beeminder has a longer [90 second timeout](https://github.com/beeminder-capstone/Nectar-Backend/blob/develop/app/workers/beeminder_worker.rb#L33).

**Comment by tdulcet** [comment]
I put a 25 second timeout on fetching the current value, so the page should now load within Heroku's 30 second limit and you can add the goal. Sorry for the inconvenience.

If it takes more than 25 seconds to get the data, then you will not be able to see the current score on the goal page. However, after syncing, the last datapoint will be on the home, credentials and goal pages.

**Comment by MarkG000** [comment]
Tried it again. On first load I got the page normally along with a timeout message to try again later. Refreshing gave me a number of 4150. A couple of refreshes didn't provide a different number. Seems low but i'll check again later.

**Comment by tdulcet** [comment]
Unfortunately, it has to get your posts 100 at a time, so to get 4150 posts it has to make 42 Facebook API calls and it has to do that in less than 25 seconds now to avoid timing out. It all depends on how busy Facebook's (and Heroku's) servers are when you load the page. However, as I said, the actual sync with Beeminder has a much longer 90 second timeout, which is plenty of time to get the data, so you can safely ignore the timeout message and add the goal. There is not really another solution without making Nectar overly complex.

Thanks for helping me debug this! I only have 2 Facebook posts, so I obviously could not reproduce the error myself.

**Comment by MarkG000** [comment]
I still get a 4150 value today even though I made a post since yesterday. 
Anyway, I made a new goal https://www.beeminder.com/apolyton/facebook-posts#data and linked it to Nectar, we'll see how it goes :) 

I clicked "reload" on the main Nectar page and got a datapoint successfully 
The comment was "Nectar for  @ 2017-08-16 12:51:39 UTC". Is there something missing after "for"?

Perhaps you could have the content of the last post as part of the comment.

**Comment by tdulcet** [comment]
> The comment was "Nectar for @ 2017-08-16 12:51:39 UTC". Is there something missing after "for"?

The comments follow this format: https://github.com/beeminder-capstone/Nectar-Backend/blob/7b88aa24cd3f355446bc782369a216da91bda69c/app/models/datapoint.rb#L26 the same as on [Quantifier](https://github.com/tsubery/quantifier/blob/d2c8ecf8068b775232f735a5527871467439a819/app/models/datapoint.rb#L20). Some metrics have a `timestamp` value. I updated it so future comments will not include the "for" if the `timestamp` value is blank.

> Perhaps you could have the content of the last post as part of the comment.

Yes, that would be possible, but I think that would be better suited for a metric that added a separate datapoint for every post.

**Comment by tdulcet** [comment]
@MarkG76 The goal you shared seemed not to be updating (as you pointed out) and I suspect we hit some kind of limit on the number of Facebook API calls one can make in a short amount of time. I updated the Facebook integration to get 1000 posts at a time and it seems to have fixed your goal, as a new datapoint was just added with a value of 4229 (hopefully it will not cause other issues).

**Comment by tdulcet** [comment]
@MarkG76 Two more datapoints were added to your goal, so I am going to mark this issue as closed. Thanks again for your help debugging this!

**Comment by MarkG000** [comment]
Glad to help!
